import 'package:flutter/material.dart';

import '../app_theme_colors.dart';
import 'app_color_palette.dart';

/// Deep Sea palette — `0d1b2a · 1b263b · 415a77 · 778da9 · e0e1dd`
const kDeepSeaPalette = AppColorPaletteDefinition(
  id: AppColorPaletteId.deepSea,
  nameKey: 'paletteDeepSea',
  previewStops: [
    Color(0xFF0d1b2a),
    Color(0xFF1b263b),
    Color(0xFF415a77),
    Color(0xFF778da9),
    Color(0xFFe0e1dd),
  ],
  light: AppPaletteScheme(
    accent: AppAccentColors(
      primary: Color(0xFF415a77),
      primaryDeep: Color(0xFF0d1b2a),
      primaryLight: Color(0xFFd9e2ea),
      primaryAccent: Color(0xFF778da9),
      onPrimary: Colors.white,
    ),
    surfaces: AppThemeColors(
      scaffoldBackground: Color(0xFFEEEFEC),
      surface: Color(0xFFFFFFFF),
      surfaceElevated: Color(0xFFF5F5F3),
      surfaceVariant: Color(0xFFE8EAE6),
      cardBorder: Color(0xFFD0D2CE),
      cardShadow: Color(0x0D000000),
      cardShadowSky: Color(0x14415a77),
      divider: Color(0xFFD4D6D2),
      textPrimary: Color(0xFF0d1b2a),
      textSecondary: Color(0xFF2B3B4E),
      textMuted: Color(0xFF5A6A7A),
      inputText: Color(0xFF0d1b2a),
      inputHint: Color(0xFF5A6A7A),
      inputBorder: Color(0xFFBEC3C8),
      inputFill: Color(0xFFEDF0F3),
      authGradientTop: Color(0xFFD9E2EA),
      authGradientBottom: Color(0xFFEEEFEC),
      navBarBackground: Color(0xFFFFFFFF),
      searchFieldFill: Color(0xFFDDE3E9),
      accentSurface: Color(0xFFD9E2EA),
      accentSurfaceBorder: Color(0xFF778da9),
      dropdownBackground: Color(0xFFFFFFFF),
      onPrimary: Colors.white,
    ),
  ),
  dark: AppPaletteScheme(
    accent: AppAccentColors(
      primary: Color(0xFF778da9),
      primaryDeep: Color(0xFF415a77),
      primaryLight: Color(0xFF1F3550),
      primaryAccent: Color(0xFF9AAFC3),
      onPrimary: Colors.white,
    ),
    surfaces: AppThemeColors(
      scaffoldBackground: Color(0xFF0d1b2a),
      surface: Color(0xFF1b263b),
      surfaceElevated: Color(0xFF243350),
      surfaceVariant: Color(0xFF1E2F44),
      cardBorder: Color(0xFF2E4060),
      cardShadow: Color(0x40000000),
      cardShadowSky: Color(0x26000000),
      divider: Color(0xFF253650),
      textPrimary: Color(0xFFe0e1dd),
      textSecondary: Color(0xFFB8BABC),
      textMuted: Color(0xFF778da9),
      inputText: Color(0xFFe0e1dd),
      inputHint: Color(0xFF778da9),
      inputBorder: Color(0xFF2E4060),
      inputFill: Color(0xFF162233),
      authGradientTop: Color(0xFF0d1b2a),
      authGradientBottom: Color(0xFF1b263b),
      navBarBackground: Color(0xFF162030),
      searchFieldFill: Color(0xFF162233),
      accentSurface: Color(0xFF1F3550),
      accentSurfaceBorder: Color(0xFF778da9),
      dropdownBackground: Color(0xFF1b263b),
      onPrimary: Colors.white,
    ),
  ),
);
